name: 'prow-github-actions'
description: 'Prow inspired github CI/CD actions'
author: 'John McBride'
inputs:
  github-token:
    description: "Github token"
    required: true
  prow-commands:
    description: "Comment keywords/commands to look for. Space delimited. Expect commands on own line."
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
